"""db05_add_check_constraints

Revision ID: 6a4c776e7fb0
Revises: 2a0ba39df96a
Create Date: 2026-04-19 13:35:56.957403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '6a4c776e7fb0'
down_revision: Union[str, Sequence[str], None] = '2a0ba39df96a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Limpiar tablas temporales huérfanas de intentos fallidos anteriores
    bind = op.get_bind()
    for tmp_table in ('_alembic_tmp_ausencias', '_alembic_tmp_configuracion',
                      '_alembic_tmp_cursos_escolares', '_alembic_tmp_guardias',
                      '_alembic_tmp_profesores', '_alembic_tmp_zonas'):
        bind.execute(text(f'DROP TABLE IF EXISTS "{tmp_table}"'))

    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('ausencias', schema=None, recreate='always') as batch_op:
        # batch_op.drop_index(batch_op.f('idx_ausencias_activa'))
        # batch_op.drop_index(batch_op.f('idx_ausencias_fechas'))
        # batch_op.drop_index(batch_op.f('idx_ausencias_profesor'))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_ausencias_profesor', 'profesores', ['profesor_id'], ['id'], ondelete='CASCADE')
        batch_op.create_check_constraint("ck_ausencia_tipo", "tipo IN ('baja_medica','permiso','vacaciones','otros')")
        batch_op.create_check_constraint("ck_ausencia_fechas", "fecha_fin >= fecha_inicio")

    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.alter_column('anio_inicio_curso',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_check_constraint("ck_config_ajuste_tutores", "ajuste_tutores > 0")
        batch_op.create_check_constraint("ck_config_ajuste_no_tutores", "ajuste_no_tutores > 0")

    with op.batch_alter_table('cursos_escolares', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_anio_curso', ['anio_inicio', 'anio_fin'])

    with op.batch_alter_table('guardias', schema=None) as batch_op:
        batch_op.alter_column('profesor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('zona_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        # batch_op.drop_index(batch_op.f('idx_guardias_fecha'))
        # batch_op.drop_index(batch_op.f('idx_guardias_fecha_turno'))
        # batch_op.drop_index(batch_op.f('idx_guardias_profesor'))
        # batch_op.drop_index(batch_op.f('idx_guardias_turno'))
        # batch_op.drop_index(batch_op.f('idx_guardias_zona'))
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_guardias_profesor', 'profesores', ['profesor_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_guardias_zona', 'zonas', ['zona_id'], ['id'], ondelete='CASCADE')
        batch_op.create_check_constraint("ck_guardia_turno", "turno IN ('ma\u00f1ana','tarde')")
        batch_op.create_check_constraint("ck_guardia_recreo_positivo", "recreo >= 1")

    with op.batch_alter_table('profesores', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('curso_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_profesores_curso_id', ['curso_id'], unique=False)
        batch_op.create_foreign_key('fk_profesores_zona_preferida', 'zonas', ['zona_preferida_id'], ['id'])
        batch_op.create_foreign_key('fk_profesores_curso', 'cursos_escolares', ['curso_id'], ['id'])
        batch_op.create_check_constraint("ck_profesor_turno", "turno IN ('ma\u00f1ana','tarde','completo','mixto')")
        batch_op.create_check_constraint("ck_profesor_porcentaje", "porcentaje_jornada >= 0 AND porcentaje_jornada <= 100")
        batch_op.create_check_constraint("ck_profesor_horas_contrato", "horas_contrato >= 0")

    with op.batch_alter_table('zonas', schema=None, recreate='always') as batch_op:
        batch_op.create_check_constraint("ck_zona_capacidad", "capacidad_profesores IS NULL OR capacidad_profesores >= 1")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_profesores_zona_preferida'), 'zonas', ['zona_preferida_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index('ix_profesores_curso_id')
        batch_op.drop_column('curso_id')

    with op.batch_alter_table('guardias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'profesores', ['profesor_id'], ['id'])
        batch_op.create_foreign_key(None, 'zonas', ['zona_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_guardias_zona'), ['zona_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_guardias_turno'), ['turno'], unique=False)
        batch_op.create_index(batch_op.f('idx_guardias_profesor'), ['profesor_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_guardias_fecha_turno'), ['fecha', 'turno'], unique=False)
        batch_op.create_index(batch_op.f('idx_guardias_fecha'), ['fecha'], unique=False)
        batch_op.alter_column('zona_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('profesor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cursos_escolares', schema=None) as batch_op:
        batch_op.drop_constraint('uq_anio_curso', type_='unique')

    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.alter_column('anio_inicio_curso',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ausencias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'profesores', ['profesor_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_ausencias_profesor'), ['profesor_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ausencias_fechas'), ['fecha_inicio', 'fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('idx_ausencias_activa'), ['activa'], unique=False)

    op.create_table('profesor_recreos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profesor_id', sa.INTEGER(), nullable=False),
    sa.Column('recreo_numero', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profesor_recreos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prof_recreos_profesor_id'), ['profesor_id'], unique=False)

    op.create_table('profesor_dias_semana',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profesor_id', sa.INTEGER(), nullable=False),
    sa.Column('dia_semana', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profesor_dias_semana', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prof_dias_semana_profesor_id'), ['profesor_id'], unique=False)

    # ### end Alembic commands ###
