"""initial migration

Revision ID: f8c079469533
Revises: 
Create Date: 2025-10-14 21:42:02.473519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c079469533'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio_curso', sa.Date(), nullable=False),
    sa.Column('fecha_fin_curso', sa.Date(), nullable=False),
    sa.Column('hora_recreo1_manana', sa.Time(), nullable=False),
    sa.Column('hora_recreo2_manana', sa.Time(), nullable=False),
    sa.Column('hora_recreo1_tarde', sa.Time(), nullable=True),
    sa.Column('hora_recreo2_tarde', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profesores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellidos', sa.String(), nullable=False),
    sa.Column('horas_contrato', sa.Float(), nullable=False),
    sa.Column('porcentaje_jornada', sa.Float(), nullable=False),
    sa.Column('turno', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zonas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_zona', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('turno', sa.String(), nullable=False),
    sa.Column('recreo', sa.Integer(), nullable=False),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guardias')
    op.drop_table('zonas')
    op.drop_table('profesores')
    op.drop_table('configuracion')
    # ### end Alembic commands ###
